-- Meaning Graph schema
-- Applied via foundation/db.py apply_schema()

CREATE SCHEMA IF NOT EXISTS meaning_graph;

CREATE TABLE IF NOT EXISTS meaning_graph.nodes (
    id          TEXT PRIMARY KEY,
    label       TEXT NOT NULL,
    kind        TEXT NOT NULL CHECK (
        kind IN ('source', 'story', 'motif', 'concept', 'question', 'nature_pattern')
    ),
    tradition   TEXT NOT NULL DEFAULT '',
    summary     TEXT NOT NULL DEFAULT '',
    age_min     INTEGER NOT NULL DEFAULT 5,
    age_max     INTEGER NOT NULL DEFAULT 10,
    tags        TEXT[] NOT NULL DEFAULT '{}',
    metadata    JSONB NOT NULL DEFAULT '{}'::jsonb
);

CREATE INDEX IF NOT EXISTS meaning_nodes_kind_tradition
    ON meaning_graph.nodes (kind, tradition);

CREATE INDEX IF NOT EXISTS meaning_nodes_age
    ON meaning_graph.nodes (age_min, age_max);

CREATE TABLE IF NOT EXISTS meaning_graph.edges (
    from_id     TEXT NOT NULL REFERENCES meaning_graph.nodes(id) ON DELETE CASCADE,
    to_id       TEXT NOT NULL REFERENCES meaning_graph.nodes(id) ON DELETE CASCADE,
    relation    TEXT NOT NULL,
    weight      REAL NOT NULL DEFAULT 1.0,
    rationale   TEXT NOT NULL DEFAULT '',
    metadata    JSONB NOT NULL DEFAULT '{}'::jsonb,
    PRIMARY KEY (from_id, to_id, relation)
);

CREATE INDEX IF NOT EXISTS meaning_edges_from
    ON meaning_graph.edges (from_id);

CREATE INDEX IF NOT EXISTS meaning_edges_to
    ON meaning_graph.edges (to_id);

CREATE TABLE IF NOT EXISTS meaning_graph.story_puzzles (
    id                TEXT PRIMARY KEY,
    story_id          TEXT NOT NULL REFERENCES meaning_graph.nodes(id) ON DELETE CASCADE,
    title             TEXT NOT NULL,
    age_min           INTEGER NOT NULL DEFAULT 5,
    age_max           INTEGER NOT NULL DEFAULT 10,
    setup             TEXT NOT NULL DEFAULT '',
    suspense_question TEXT NOT NULL DEFAULT '',
    choice_a          TEXT NOT NULL DEFAULT '',
    choice_b          TEXT NOT NULL DEFAULT '',
    choice_c          TEXT NOT NULL DEFAULT '',
    parent_hint       TEXT NOT NULL DEFAULT '',
    parth_reasoning   TEXT NOT NULL DEFAULT '',
    moral_tension     TEXT NOT NULL DEFAULT '',
    nature_bridge     TEXT NOT NULL DEFAULT '',
    deeper_question   TEXT NOT NULL DEFAULT '',
    concept_ids       TEXT[] NOT NULL DEFAULT '{}',
    motif_ids         TEXT[] NOT NULL DEFAULT '{}',
    metadata          JSONB NOT NULL DEFAULT '{}'::jsonb
);

CREATE INDEX IF NOT EXISTS meaning_puzzles_story
    ON meaning_graph.story_puzzles (story_id);

CREATE INDEX IF NOT EXISTS meaning_puzzles_age
    ON meaning_graph.story_puzzles (age_min, age_max);

INSERT INTO meaning_graph.nodes
    (id, label, kind, tradition, summary, age_min, age_max, tags, metadata)
VALUES
    ('source_aesop', 'Aesop Fables', 'source', 'aesop',
     $$Short animal tales that compress everyday choices into memorable moral patterns.$$,
     5, 10, ARRAY['fable','animal','moral','choice'], '{}'::jsonb),
    ('source_panchatantra', 'Panchatantra', 'source', 'panchatantra',
     $$Layered Indian animal stories about friendship, strategy, trust, and consequences.$$,
     5, 10, ARRAY['fable','strategy','friendship','trust'], '{}'::jsonb),
    ('source_bible_parables', 'Bible Parables', 'source', 'bible',
     $$Short teaching stories that use ordinary life to ask what love, mercy, and faithfulness require.$$,
     5, 10, ARRAY['parable','mercy','service','faithfulness'], '{}'::jsonb),
    ('source_vedas_upanishads', 'Vedas and Upanishads', 'source', 'vedic',
     $$Indian wisdom literature that asks what is real, what matters, and how attention changes the self.$$,
     7, 10, ARRAY['wisdom','attention','self','truth'], '{}'::jsonb),
    ('source_indian_epic_wisdom', 'Indian Epic Wisdom', 'source', 'indian_epic',
     $$Epic scenes that put duty, courage, family, doubt, and choice under pressure.$$,
     7, 10, ARRAY['duty','choice','courage','family'], '{}'::jsonb),
    ('source_shakespeare', 'Shakespeare', 'source', 'shakespeare',
     $$Plays that make hidden motives visible through choices, language, loyalty, and consequence.$$,
     8, 10, ARRAY['drama','language','motive','consequence'], '{}'::jsonb),

    ('story_aesop_fox_grapes', 'The Fox and the Grapes', 'story', 'aesop',
     $$A hungry fox cannot reach grapes, then decides they were probably not worth having.$$,
     5, 10, ARRAY['desire','excuse','truth','self-control'], '{}'::jsonb),
    ('story_aesop_tortoise_hare', 'The Tortoise and the Hare', 'story', 'aesop',
     $$A fast runner becomes careless while a slow runner keeps going until the race is finished.$$,
     5, 10, ARRAY['patience','attention','pace','humility'], '{}'::jsonb),
    ('story_panchatantra_monkey_crocodile', 'The Monkey and the Crocodile', 'story', 'panchatantra',
     $$A monkey must think quickly when a false friend reveals a dangerous plan.$$,
     6, 10, ARRAY['trust','deception','quick-thinking','friendship'], '{}'::jsonb),
    ('story_bible_good_samaritan', 'The Good Samaritan', 'story', 'bible',
     $$A traveler helps a wounded stranger when others pass by, widening the meaning of neighbor.$$,
     6, 10, ARRAY['compassion','neighbor','help','fairness'], '{}'::jsonb),
    ('story_bible_lost_sheep', 'The Lost Sheep', 'story', 'bible',
     $$A shepherd notices one missing sheep and treats recovery as worth special attention.$$,
     5, 9, ARRAY['care','attention','belonging','persistence'], '{}'::jsonb),
    ('story_upanishad_nachiketa', 'Nachiketa Questioning Yama', 'story', 'vedic',
     $$A child questioner refuses easy gifts because he wants to understand what truly lasts.$$,
     8, 10, ARRAY['truth','mortality','desire','courage'], '{}'::jsonb),
    ('story_gita_arjuna_choice', 'Arjuna at the Crossroads', 'story', 'indian_epic',
     $$A capable warrior freezes before a painful duty and must examine fear, role, and right action.$$,
     8, 10, ARRAY['duty','fear','courage','choice'], '{}'::jsonb),
    ('story_shakespeare_king_lear_flattery', 'King Lear and the Honest Daughter', 'story', 'shakespeare',
     $$A ruler trusts loud flattery and misses the quieter love that tells the truth.$$,
     8, 10, ARRAY['truth','flattery','family','evidence'], '{}'::jsonb),
    ('story_shakespeare_macbeth_ambition', 'Macbeth and Restless Want', 'story', 'shakespeare',
     $$A brave person lets unchecked ambition shrink his world until fear begins to rule him.$$,
     9, 10, ARRAY['ambition','fear','consequence','self-control'], '{}'::jsonb),

    ('motif_desire', 'Desire', 'motif', '',
     $$Wanting something can energize effort, but it can also bend attention and excuse-making.$$,
     5, 10, ARRAY['want','desire','attention'], '{}'::jsonb),
    ('motif_patience', 'Patience', 'motif', '',
     $$Staying with a good path even when it is slow or not immediately exciting.$$,
     5, 10, ARRAY['pace','wait','steady'], '{}'::jsonb),
    ('motif_compassion', 'Compassion', 'motif', '',
     $$Noticing another being's need and letting that noticing change what you do.$$,
     5, 10, ARRAY['help','care','mercy'], '{}'::jsonb),
    ('motif_truth', 'Truthfulness', 'motif', '',
     $$Saying and seeking what is real, even when a smaller story feels easier.$$,
     5, 10, ARRAY['truth','honesty','evidence'], '{}'::jsonb),
    ('motif_courage', 'Courage', 'motif', '',
     $$Moving toward the right thing while fear is still present.$$,
     6, 10, ARRAY['bravery','fear','choice'], '{}'::jsonb),
    ('motif_identity', 'Identity', 'motif', '',
     $$The story a child carries about who they are and what they are becoming.$$,
     6, 10, ARRAY['self','role','becoming'], '{}'::jsonb),
    ('motif_attention', 'Attention', 'motif', '',
     $$What the mind keeps returning to becomes stronger in memory and action.$$,
     5, 10, ARRAY['focus','mind','memory'], '{}'::jsonb),
    ('motif_consequence', 'Consequence', 'motif', '',
     $$Choices travel forward and shape the next set of choices.$$,
     5, 10, ARRAY['cause','effect','result'], '{}'::jsonb),
    ('motif_reciprocity', 'Reciprocity', 'motif', '',
     $$Relationships strengthen when giving, receiving, and trust stay balanced.$$,
     6, 10, ARRAY['friendship','trust','exchange'], '{}'::jsonb),
    ('motif_perspective', 'Perspective Taking', 'motif', '',
     $$Imagining how a situation looks from another mind before acting.$$,
     6, 10, ARRAY['empathy','view','other'], '{}'::jsonb),

    ('concept_delayed_gratification', 'Delayed Gratification', 'concept', '',
     $$Choosing a larger later good over a smaller immediate reward.$$,
     6, 10, ARRAY['wait','reward','self-control'], '{}'::jsonb),
    ('concept_cause_effect', 'Cause and Effect', 'concept', '',
     $$A decision creates conditions that make some future outcomes more likely.$$,
     5, 10, ARRAY['cause','effect','sequence'], '{}'::jsonb),
    ('concept_evidence_vs_appearance', 'Evidence vs Appearance', 'concept', '',
     $$The first thing that looks true may not be what the evidence supports.$$,
     6, 10, ARRAY['evidence','appearance','reasoning'], '{}'::jsonb),
    ('concept_self_control', 'Self-Control', 'concept', '',
     $$The skill of pausing, naming an urge, and choosing the next action.$$,
     5, 10, ARRAY['pause','choice','urge'], '{}'::jsonb),
    ('concept_fairness', 'Fairness', 'concept', '',
     $$Asking what each person needs and what each person owes.$$,
     5, 10, ARRAY['justice','share','need'], '{}'::jsonb),
    ('concept_mortality', 'Mortality', 'concept', '',
     $$The hard idea that living things change and end, which can make choices feel precious.$$,
     8, 10, ARRAY['life','death','meaning'], '{}'::jsonb),
    ('concept_trust', 'Trust', 'concept', '',
     $$A confidence built from truth, care, and repeated behavior.$$,
     5, 10, ARRAY['friend','promise','reliability'], '{}'::jsonb),
    ('concept_signal_deception', 'Signal and Deception', 'concept', '',
     $$Words and actions can be signals; some signals help, and some hide intent.$$,
     7, 10, ARRAY['signal','deception','intent'], '{}'::jsonb),
    ('concept_second_order_thinking', 'Second-Order Thinking', 'concept', '',
     $$Thinking not only about what you want, but what happens after you get it.$$,
     8, 10, ARRAY['future','strategy','consequence'], '{}'::jsonb),
    ('concept_moral_courage', 'Moral Courage', 'concept', '',
     $$Doing or saying what is right when approval is uncertain.$$,
     7, 10, ARRAY['truth','courage','approval'], '{}'::jsonb),

    ('nature_pattern_seed_to_tree', 'Seed to Tree', 'nature_pattern', '',
     $$Small steady inputs can become large structures when time and conditions support them.$$,
     5, 10, ARRAY['growth','patience','time'], '{}'::jsonb),
    ('nature_pattern_predator_prey', 'Predator and Prey Signals', 'nature_pattern', '',
     $$Living things read signals from others; survival can depend on noticing what is real.$$,
     7, 10, ARRAY['signal','attention','deception'], '{}'::jsonb),
    ('nature_pattern_echo_feedback', 'Echo and Feedback', 'nature_pattern', '',
     $$A signal that returns can amplify, correct, or distort what was first sent.$$,
     6, 10, ARRAY['feedback','echo','truth'], '{}'::jsonb),
    ('nature_pattern_river_path', 'River Path', 'nature_pattern', '',
     $$A river shapes its path through many small movements, obstacles, and returns.$$,
     5, 10, ARRAY['path','persistence','adaptation'], '{}'::jsonb),
    ('nature_pattern_neural_rewiring', 'Neural Rewiring', 'nature_pattern', '',
     $$Repeated attention strengthens some routes in the brain while unused routes weaken.$$,
     7, 10, ARRAY['brain','attention','memory'], '{}'::jsonb),
    ('nature_pattern_forest_help', 'Forest Resource Sharing', 'nature_pattern', '',
     $$A forest can survive better when roots, soil, and organisms move resources where needed.$$,
     7, 10, ARRAY['help','network','care'], '{}'::jsonb),

    ('question_what_is_enough', 'What is enough?', 'question', '',
     $$A question about when wanting helps life and when wanting starts ruling life.$$,
     6, 10, ARRAY['desire','enough','choice'], '{}'::jsonb),
    ('question_who_deserves_help', 'Who deserves help?', 'question', '',
     $$A question that tests whether care stops at family, friends, group, or comfort.$$,
     6, 10, ARRAY['help','neighbor','fairness'], '{}'::jsonb),
    ('question_brave_choice', 'What makes a choice brave?', 'question', '',
     $$A question that separates loud confidence from right action under fear.$$,
     7, 10, ARRAY['bravery','fear','action'], '{}'::jsonb),
    ('question_when_truth_hurts', 'When should truth be spoken?', 'question', '',
     $$A question about honesty, kindness, timing, and responsibility.$$,
     7, 10, ARRAY['truth','kindness','timing'], '{}'::jsonb),
    ('question_how_mind_changes', 'How does a mind change?', 'question', '',
     $$A question about attention, repetition, memory, and the stories we practice.$$,
     7, 10, ARRAY['mind','memory','attention'], '{}'::jsonb)
ON CONFLICT (id) DO UPDATE SET
    label = EXCLUDED.label,
    kind = EXCLUDED.kind,
    tradition = EXCLUDED.tradition,
    summary = EXCLUDED.summary,
    age_min = EXCLUDED.age_min,
    age_max = EXCLUDED.age_max,
    tags = EXCLUDED.tags,
    metadata = EXCLUDED.metadata;

INSERT INTO meaning_graph.edges
    (from_id, to_id, relation, weight, rationale, metadata)
VALUES
    ('source_aesop', 'story_aesop_fox_grapes', 'contains', 1.0, 'Source contains the story.', '{}'::jsonb),
    ('source_aesop', 'story_aesop_tortoise_hare', 'contains', 1.0, 'Source contains the story.', '{}'::jsonb),
    ('source_panchatantra', 'story_panchatantra_monkey_crocodile', 'contains', 1.0, 'Source contains the story.', '{}'::jsonb),
    ('source_bible_parables', 'story_bible_good_samaritan', 'contains', 1.0, 'Source contains the story.', '{}'::jsonb),
    ('source_bible_parables', 'story_bible_lost_sheep', 'contains', 1.0, 'Source contains the story.', '{}'::jsonb),
    ('source_vedas_upanishads', 'story_upanishad_nachiketa', 'contains', 1.0, 'Source contains the story.', '{}'::jsonb),
    ('source_indian_epic_wisdom', 'story_gita_arjuna_choice', 'contains', 1.0, 'Source contains the story.', '{}'::jsonb),
    ('source_shakespeare', 'story_shakespeare_king_lear_flattery', 'contains', 1.0, 'Source contains the story.', '{}'::jsonb),
    ('source_shakespeare', 'story_shakespeare_macbeth_ambition', 'contains', 1.0, 'Source contains the story.', '{}'::jsonb),

    ('story_aesop_fox_grapes', 'motif_desire', 'teaches', 0.95, 'The fox changes the story after desire is frustrated.', '{}'::jsonb),
    ('story_aesop_fox_grapes', 'motif_truth', 'teaches', 0.9, 'The child can compare honest disappointment with an excuse.', '{}'::jsonb),
    ('story_aesop_fox_grapes', 'concept_evidence_vs_appearance', 'teaches', 0.85, 'What the fox says does not match the evidence of wanting.', '{}'::jsonb),
    ('story_aesop_fox_grapes', 'question_what_is_enough', 'asks', 0.8, 'The puzzle opens the difference between wanting and judging.', '{}'::jsonb),

    ('story_aesop_tortoise_hare', 'motif_patience', 'teaches', 1.0, 'The slow runner wins by staying with the path.', '{}'::jsonb),
    ('story_aesop_tortoise_hare', 'motif_attention', 'teaches', 0.9, 'The fast runner loses attention before the race is done.', '{}'::jsonb),
    ('story_aesop_tortoise_hare', 'concept_delayed_gratification', 'teaches', 0.85, 'Steady progress beats immediate pride.', '{}'::jsonb),
    ('story_aesop_tortoise_hare', 'nature_pattern_seed_to_tree', 'mirrors', 0.8, 'Small steady growth can overtake dramatic starts.', '{}'::jsonb),

    ('story_panchatantra_monkey_crocodile', 'concept_trust', 'teaches', 0.9, 'Friendship is tested by repeated truthful behavior.', '{}'::jsonb),
    ('story_panchatantra_monkey_crocodile', 'concept_signal_deception', 'teaches', 0.95, 'The crocodile sends friendly signals while hiding intent.', '{}'::jsonb),
    ('story_panchatantra_monkey_crocodile', 'motif_reciprocity', 'teaches', 0.8, 'The story asks what fair exchange means in friendship.', '{}'::jsonb),
    ('story_panchatantra_monkey_crocodile', 'nature_pattern_predator_prey', 'mirrors', 0.85, 'The monkey must read danger signals quickly.', '{}'::jsonb),

    ('story_bible_good_samaritan', 'motif_compassion', 'teaches', 1.0, 'The helper lets another person''s need interrupt his plan.', '{}'::jsonb),
    ('story_bible_good_samaritan', 'motif_perspective', 'teaches', 0.9, 'The child can imagine the wounded traveler''s view.', '{}'::jsonb),
    ('story_bible_good_samaritan', 'concept_fairness', 'teaches', 0.85, 'The story widens fairness beyond familiar groups.', '{}'::jsonb),
    ('story_bible_good_samaritan', 'question_who_deserves_help', 'asks', 0.95, 'The central question is how wide care should become.', '{}'::jsonb),
    ('story_bible_good_samaritan', 'nature_pattern_forest_help', 'mirrors', 0.75, 'Systems survive when help moves to the vulnerable point.', '{}'::jsonb),

    ('story_bible_lost_sheep', 'motif_attention', 'teaches', 0.9, 'The shepherd notices the one that is missing.', '{}'::jsonb),
    ('story_bible_lost_sheep', 'motif_compassion', 'teaches', 0.8, 'Care becomes active search.', '{}'::jsonb),
    ('story_bible_lost_sheep', 'nature_pattern_river_path', 'mirrors', 0.7, 'Search may require returning and trying another path.', '{}'::jsonb),

    ('story_upanishad_nachiketa', 'motif_truth', 'teaches', 1.0, 'The child questioner keeps returning to the deepest question.', '{}'::jsonb),
    ('story_upanishad_nachiketa', 'motif_courage', 'teaches', 0.95, 'He continues asking despite fear and temptation.', '{}'::jsonb),
    ('story_upanishad_nachiketa', 'concept_mortality', 'teaches', 0.9, 'The story makes impermanence discussable for older children.', '{}'::jsonb),
    ('story_upanishad_nachiketa', 'question_what_is_enough', 'asks', 0.9, 'Temporary gifts are contrasted with lasting understanding.', '{}'::jsonb),

    ('story_gita_arjuna_choice', 'motif_courage', 'teaches', 0.95, 'Courage includes examining fear before action.', '{}'::jsonb),
    ('story_gita_arjuna_choice', 'motif_identity', 'teaches', 0.85, 'Role and self-understanding become part of the choice.', '{}'::jsonb),
    ('story_gita_arjuna_choice', 'concept_moral_courage', 'teaches', 0.9, 'The story distinguishes comfort from responsible action.', '{}'::jsonb),
    ('story_gita_arjuna_choice', 'question_brave_choice', 'asks', 0.9, 'The scene asks what brave action is when every path hurts.', '{}'::jsonb),

    ('story_shakespeare_king_lear_flattery', 'motif_truth', 'teaches', 0.9, 'Quiet honesty is contrasted with loud praise.', '{}'::jsonb),
    ('story_shakespeare_king_lear_flattery', 'concept_evidence_vs_appearance', 'teaches', 0.9, 'Lear confuses appearance with evidence of love.', '{}'::jsonb),
    ('story_shakespeare_king_lear_flattery', 'question_when_truth_hurts', 'asks', 0.85, 'The honest daughter raises the cost of truthful speech.', '{}'::jsonb),
    ('story_shakespeare_king_lear_flattery', 'nature_pattern_echo_feedback', 'mirrors', 0.75, 'Flattery works like distorted feedback.', '{}'::jsonb),

    ('story_shakespeare_macbeth_ambition', 'motif_desire', 'teaches', 0.95, 'Wanting power becomes a trap rather than a compass.', '{}'::jsonb),
    ('story_shakespeare_macbeth_ambition', 'motif_consequence', 'teaches', 0.95, 'One choice narrows the next choices.', '{}'::jsonb),
    ('story_shakespeare_macbeth_ambition', 'concept_second_order_thinking', 'teaches', 0.9, 'The story asks what happens after the wanted thing is gained.', '{}'::jsonb),
    ('story_shakespeare_macbeth_ambition', 'question_what_is_enough', 'asks', 0.85, 'Unchecked wanting keeps moving the finish line.', '{}'::jsonb),

    ('motif_attention', 'nature_pattern_neural_rewiring', 'bridges_to', 1.0, 'Repeated attention changes what the brain can do easily.', '{}'::jsonb),
    ('motif_patience', 'nature_pattern_river_path', 'bridges_to', 0.8, 'Both patience and rivers shape outcomes by continuing.', '{}'::jsonb),
    ('motif_compassion', 'nature_pattern_forest_help', 'bridges_to', 0.85, 'Care can be described as moving resources toward need.', '{}'::jsonb),
    ('motif_truth', 'nature_pattern_echo_feedback', 'bridges_to', 0.8, 'Truth works as corrective feedback.', '{}'::jsonb),
    ('motif_desire', 'concept_self_control', 'bridges_to', 0.9, 'Desire needs pause and choice to become wise action.', '{}'::jsonb),
    ('motif_consequence', 'concept_cause_effect', 'bridges_to', 0.9, 'Consequences are cause and effect in moral time.', '{}'::jsonb),
    ('motif_courage', 'concept_moral_courage', 'bridges_to', 0.95, 'Courage becomes moral when it serves the right thing.', '{}'::jsonb),
    ('concept_self_control', 'nature_pattern_neural_rewiring', 'bridges_to', 0.75, 'Practice makes pausing more available.', '{}'::jsonb),
    ('question_how_mind_changes', 'nature_pattern_neural_rewiring', 'bridges_to', 0.95, 'The brain pattern answers the question through practice and attention.', '{}'::jsonb),

    ('story_aesop_fox_grapes', 'story_shakespeare_macbeth_ambition', 'echoes', 0.8, 'Both stories show desire distorting judgment — one wanting frustrated and re-storied as not-wanted, one wanting granted and still not satisfied.', '{}'::jsonb),
    ('story_aesop_tortoise_hare', 'story_bible_lost_sheep', 'echoes', 0.75, 'Both turn on what attention notices or misses — a runner''s attention lapsing before the finish, a shepherd''s attention catching the one that is missing.', '{}'::jsonb),
    ('story_bible_good_samaritan', 'story_panchatantra_monkey_crocodile', 'echoes', 0.75, 'Both ask the child to imagine a situation from another''s point of view before acting — a wounded stranger''s view, a supposed friend''s hidden intent.', '{}'::jsonb)
ON CONFLICT (from_id, to_id, relation) DO UPDATE SET
    weight = EXCLUDED.weight,
    rationale = EXCLUDED.rationale,
    metadata = EXCLUDED.metadata;

INSERT INTO meaning_graph.story_puzzles
    (id, story_id, title, age_min, age_max, setup, suspense_question,
     choice_a, choice_b, choice_c, parent_hint, parth_reasoning,
     moral_tension, nature_bridge, deeper_question, concept_ids, motif_ids, metadata)
VALUES
    ('puzzle_tortoise_hare_pace', 'story_aesop_tortoise_hare',
     'The Race That Slowed Down',
     5, 10,
     $$A very fast runner laughs because the race looks easy. A slow runner does not argue and simply starts.$$,
     $$At the halfway point, why is the race still dangerous for the fast runner?$$,
     $$Speed always wins once it starts ahead.$$,
     $$Pride can make attention fall asleep before the work is done.$$,
     $$The slow runner secretly becomes faster.$$,
     $$Ask the child to predict the hidden danger before revealing the ending: the danger is not weak legs, it is wandering attention.$$,
     $$Parth should guide the child from "fast versus slow" to "steady attention versus careless attention".$$,
     $$Talent feels exciting, but effort needs attention until the end.$$,
     $$Like a seed becoming a tree, small steady growth can beat a dramatic start.$$,
     $$Where in your life does steady practice beat showing off?$$,
     ARRAY['concept_delayed_gratification','concept_self_control'],
     ARRAY['motif_patience','motif_attention'],
     '{}'::jsonb),

    ('puzzle_fox_grapes_truth', 'story_aesop_fox_grapes',
     'The Grapes That Changed Taste',
     5, 10,
     $$A fox wants grapes badly, jumps again and again, then walks away saying the grapes were probably bad anyway.$$,
     $$Did the grapes change, or did the fox change the story?$$,
     $$The grapes became bad while the fox was jumping.$$,
     $$The fox may be protecting his pride from disappointment.$$,
     $$The fox learned that fruit is never useful.$$,
     $$Pause before the moral and ask what evidence the child has: what did the fox do before speaking?$$,
     $$Parth should name the difference between a feeling, a fact, and an excuse.$$,
     $$It is painful to want and fail; truthfulness starts by naming that pain without inventing a smaller story.$$,
     $$An echo can distort a sound; pride can distort the story we hear in our own mind.$$,
     $$When is it brave to say, "I wanted that, but I could not reach it yet"?$$,
     ARRAY['concept_evidence_vs_appearance','concept_self_control'],
     ARRAY['motif_desire','motif_truth'],
     '{}'::jsonb),

    ('puzzle_monkey_crocodile_trust', 'story_panchatantra_monkey_crocodile',
     'The Friend Who Asked Too Late',
     6, 10,
     $$A monkey shares fruit with a crocodile. In the river, the crocodile reveals that the visit has a hidden purpose.$$,
     $$What should the monkey solve first: the crocodile's feelings, the missing evidence, or the immediate danger?$$,
     $$Make the crocodile feel better first.$$,
     $$Notice the immediate danger, then use clear thinking to create a way back to safety.$$,
     $$Assume all friends are dangerous forever.$$,
     $$Let the child separate trust from blind trust. A friend is not a label; friendship is repeated truthful behavior.$$,
     $$Parth should praise quick thinking while also asking what warning signs appeared earlier.$$,
     $$Kindness needs wisdom because signals can be honest or deceptive.$$,
     $$Animals survive by reading signals: movement, timing, and intent all matter.$$,
     $$How can you stay kind without ignoring evidence?$$,
     ARRAY['concept_trust','concept_signal_deception','concept_evidence_vs_appearance'],
     ARRAY['motif_reciprocity','motif_perspective'],
     '{}'::jsonb),

    ('puzzle_good_samaritan_circle', 'story_bible_good_samaritan',
     'The Circle That Became Bigger',
     6, 10,
     $$A hurt traveler lies by the road. Some people pass by, and one unexpected person stops to help.$$,
     $$Before the helper arrives, what invisible line might stop people from helping?$$,
     $$They may think the hurt person is outside their circle of care.$$,
     $$They know the traveler has already solved the problem.$$,
     $$They are certain that kindness is never useful.$$,
     $$Ask the child to draw a small circle of care, then add one person who is easy to ignore.$$,
     $$Parth should move from "Who is my neighbor?" to "Whose need is visible to me now?"$$,
     $$Compassion tests whether care stops at comfort, group, or convenience.$$,
     $$A forest survives when resources move toward a weak spot instead of only staying with the strong parts.$$,
     $$Who became your neighbor this week because you noticed their need?$$,
     ARRAY['concept_fairness','concept_cause_effect'],
     ARRAY['motif_compassion','motif_perspective'],
     '{}'::jsonb),

    ('puzzle_lost_sheep_attention', 'story_bible_lost_sheep',
     'The Missing One',
     5, 9,
     $$A shepherd counts the group and notices that one is missing. The group is mostly safe, but one life is outside the circle.$$,
     $$Why does one missing sheep change the whole evening?$$,
     $$Because attention notices what averages hide.$$,
     $$Because the other sheep are no longer important.$$,
     $$Because counting is always more important than caring.$$,
     $$Let the child feel the suspense of the count: ninety-nine can sound complete until the missing one has a name.$$,
     $$Parth should connect attention to care: what we notice becomes what we can protect.$$,
     $$A group can look fine while one member still needs help.$$,
     $$A river search may require turning back, checking side paths, and not giving up after the first route.$$,
     $$What is one small thing adults sometimes miss because the group looks okay?$$,
     ARRAY['concept_cause_effect','concept_fairness'],
     ARRAY['motif_attention','motif_compassion'],
     '{}'::jsonb),

    ('puzzle_nachiketa_choice', 'story_upanishad_nachiketa',
     'The Gift That Was Not Enough',
     8, 10,
     $$A young questioner is offered attractive gifts, but he keeps returning to the deeper question he came to ask.$$,
     $$Why might a bright gift be a distraction instead of an answer?$$,
     $$Because every gift is bad.$$,
     $$Because a gift can quiet the question without answering it.$$,
     $$Because children should never ask hard questions.$$,
     $$Keep this gentle. The puzzle is not about frightening a child; it is about asking what lasts after excitement fades.$$,
     $$Parth should contrast temporary excitement with a question that keeps mattering tomorrow.$$,
     $$Desire can decorate a room while truth is waiting at the door.$$,
     $$Neural paths strengthen through repeated attention; the question we return to shapes the mind we build.$$,
     $$What is a question you would not trade for a toy or treat?$$,
     ARRAY['concept_mortality','concept_second_order_thinking'],
     ARRAY['motif_truth','motif_courage','motif_desire'],
     '{}'::jsonb),

    ('puzzle_arjuna_crossroads', 'story_gita_arjuna_choice',
     'The Brave Pause',
     8, 10,
     $$A skilled person reaches a moment where every path feels painful, so he stops and asks what right action requires.$$,
     $$Can pausing be brave, or is bravery only moving fast?$$,
     $$Pausing can be brave if it helps a person see clearly before acting.$$,
     $$Bravery always means rushing first.$$,
     $$A difficult feeling proves the task is wrong.$$,
     $$Ask for a real child-scale example: apologizing, telling the truth, or trying again after embarrassment.$$,
     $$Parth should distinguish avoidance from a reflective pause that prepares right action.$$,
     $$Courage is not the absence of fear; it is careful action while fear is present.$$,
     $$A river pauses at rocks by changing path, but it does not stop being a river.$$,
     $$What is one situation where a pause could make you braver?$$,
     ARRAY['concept_moral_courage','concept_second_order_thinking'],
     ARRAY['motif_courage','motif_identity'],
     '{}'::jsonb),

    ('puzzle_king_lear_truth', 'story_shakespeare_king_lear_flattery',
     'The Loudest Love',
     8, 10,
     $$A parent asks for proof of love. Some answers are loud and polished; one answer is quieter and more honest.$$,
     $$Why might the loudest answer be the least reliable evidence?$$,
     $$Because loudness and truth are different signals.$$,
     $$Because quiet people never love anyone.$$,
     $$Because evidence is unnecessary in families.$$,
     $$Have the child compare signal strength and signal honesty: a loud signal can still be distorted.$$,
     $$Parth should ask what repeated actions would prove love better than a performance.$$,
     $$Truth may sound smaller than flattery, but it can protect the relationship from illusion.$$,
     $$An echo can grow louder while becoming less accurate.$$,
     $$When should love tell the truth instead of only pleasing someone?$$,
     ARRAY['concept_evidence_vs_appearance','concept_moral_courage'],
     ARRAY['motif_truth','motif_perspective'],
     '{}'::jsonb),

    ('puzzle_macbeth_enough', 'story_shakespeare_macbeth_ambition',
     'The Crown That Moved Away',
     9, 10,
     $$A brave person gets close to power, but each success makes the next fear louder.$$,
     $$Why can getting what you want sometimes make wanting stronger?$$,
     $$Because desire can move the finish line after every win.$$,
     $$Because success always makes people bad.$$,
     $$Because fear disappears after the first success.$$,
     $$Keep the discussion child-scale: wanting the highest score, more screen time, or always being first.$$,
     $$Parth should explore second-order thinking: what changes after the wanted thing arrives?$$,
     $$Ambition needs a purpose; without one, it can turn the mind into a smaller room.$$,
     $$A feedback loop can amplify a signal until it controls the whole system.$$,
     $$How do you know when a goal is helping you grow instead of shrinking your world?$$,
     ARRAY['concept_second_order_thinking','concept_self_control'],
     ARRAY['motif_desire','motif_consequence'],
     '{}'::jsonb)
ON CONFLICT (id) DO UPDATE SET
    story_id = EXCLUDED.story_id,
    title = EXCLUDED.title,
    age_min = EXCLUDED.age_min,
    age_max = EXCLUDED.age_max,
    setup = EXCLUDED.setup,
    suspense_question = EXCLUDED.suspense_question,
    choice_a = EXCLUDED.choice_a,
    choice_b = EXCLUDED.choice_b,
    choice_c = EXCLUDED.choice_c,
    parent_hint = EXCLUDED.parent_hint,
    parth_reasoning = EXCLUDED.parth_reasoning,
    moral_tension = EXCLUDED.moral_tension,
    nature_bridge = EXCLUDED.nature_bridge,
    deeper_question = EXCLUDED.deeper_question,
    concept_ids = EXCLUDED.concept_ids,
    motif_ids = EXCLUDED.motif_ids,
    metadata = EXCLUDED.metadata;
